version: 2
updates:
- package-ecosystem: pnpm
  directory: "/project-a"
  schedule:
    interval: daily
    time: "16:50"
    timezone: "America/New_York"
  versioning-strategy: auto
- package-ecosystem: pnpm
  directory: "/project-b"
  schedule:
    interval: daily
    time: "16:50"
    timezone: "America/New_York"
  versioning-strategy: auto  